version: '3'
services:
  PWN_CHALL:
    build:
      context: .
    working_dir: /home/pwn
    container_name: PWN_CHALL
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "PORTVLAUE:6999"
    entrypoint: /etc/init.sh
